[package]
name = "sc2-macro"
version = "1.0.0"
description = "Procedural macros for rust-sc2 API"
authors.workspace = true
edition.workspace = true
repository.workspace = true
readme.workspace = true

[dependencies]
sc2-proc-macro = { path = "macro", version = "1" }
